[package]
    edition="2021"
    name   ="qbit_controller"
    version="0.1.0"

[dependencies]
    clap = "4.5.14"
    reqwest={version="0.12.5", features=["json"]}
    serde  ={version="1.0.205", features=["derive"]}
    tokio  ={version="1.39.2", features=["full"]}
